[profile.default]
src = "src"
out = "out"
libs = ["lib"]
test = "test"
script = "script"
remappings = [
    "solidity-merkle-trees/=lib/solidity-merkle-trees/src/",
    "@openzeppelin/=lib/openzeppelin-contracts/"
]
solidity-merkle-trees = { git = "https://github.com/polytope-labs/solidity-merkle-trees" }
BlockVerifier = { git = "https://github.com/Zergity/uniswap-oracle", path = "contracts/source/BlockVerifier.sol" }
BlockHashRecorder = { git = "https://github.com/Zergity/block-hash-recorder" }